all: bin/chess

bin/chess: obj/display_board.o obj/move.o obj/main.o
	gcc -Wall -Werror -o bin/chess obj/display_board.o obj/move.o obj/main.o
obj/display_board.o: scr/function/display_board.c
	gcc -Wall -Werror -c -I scr -o obj/display_board.o scr/function/display_board.c
obj/move.o: scr/function/move.c
	gcc -Wall -Werror -c -I scr -o obj/move.o scr/function/move.c
obj/main.o: scr/main/main.c
	gcc -Wall -Werror -c -I scr -o obj/main.o scr/main/main.c

PHONY : clean;

clean:
		rm -rf obj/*.o bin/chess