name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs -i && git diff --exit-code

      - name: Build application
        run: make -f MakeFile
        
      - name: Chess test
        run: make -f MakeFile test

      - name: Chess test
        run: make test